-- ****************************************************
-- ** File: led_ase_mesh1_example.vhd
-- ** Date: 11.11.2011 14:34:43
-- ** Description: 
-- **
-- ** This file was generated by Kactus2 vhdl generator
-- **
-- ****************************************************

library IEEE;
use IEEE.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.all;

entity led_ase_mesh1_example is

	port (
		clk_CLK : in std_logic;
		led_1_gpio_out : out std_logic;
		led_gpio_out : out std_logic;
		reset_RESETn : in std_logic;
		switch_1_gpio_out : in std_logic;
		switch_gpio_out : in std_logic);

end led_ase_mesh1_example;

architecture structural of led_ase_mesh1_example is

	signal led_pkt_codec_mk2_1_cmd_out_ase_mesh1_top4_1_cmd0_in : std_logic_vector(1 downto 0);
	signal led_pkt_codec_mk2_1_cmd_in_ase_mesh1_top4_1_cmd0_out : std_logic_vector(1 downto 0);
	signal led_pkt_codec_mk2_2_cmd_out_ase_mesh1_top4_1_cmd1_in : std_logic_vector(1 downto 0);
	signal led_pkt_codec_mk2_2_cmd_in_ase_mesh1_top4_1_cmd1_out : std_logic_vector(1 downto 0);
	signal switch_pkt_codec_mk2_1_cmd_out_ase_mesh1_top4_1_cmd2_in : std_logic_vector(1 downto 0);
	signal switch_pkt_codec_mk2_1_cmd_in_ase_mesh1_top4_1_cmd2_out : std_logic_vector(1 downto 0);
	signal switch_pkt_codec_mk2_2_cmd_out_ase_mesh1_top4_1_cmd3_in : std_logic_vector(1 downto 0);
	signal switch_pkt_codec_mk2_2_cmd_in_ase_mesh1_top4_1_cmd3_out : std_logic_vector(1 downto 0);
	signal led_pkt_codec_mk2_1_data_out_ase_mesh1_top4_1_data0_in : std_logic_vector(31 downto 0);
	signal led_pkt_codec_mk2_1_data_in_ase_mesh1_top4_1_data0_out : std_logic_vector(31 downto 0);
	signal led_pkt_codec_mk2_2_data_out_ase_mesh1_top4_1_data1_in : std_logic_vector(31 downto 0);
	signal led_pkt_codec_mk2_2_data_in_ase_mesh1_top4_1_data1_out : std_logic_vector(31 downto 0);
	signal switch_pkt_codec_mk2_1_data_out_ase_mesh1_top4_1_data2_in : std_logic_vector(31 downto 0);
	signal switch_pkt_codec_mk2_1_data_in_ase_mesh1_top4_1_data2_out : std_logic_vector(31 downto 0);
	signal switch_pkt_codec_mk2_2_data_out_ase_mesh1_top4_1_data3_in : std_logic_vector(31 downto 0);
	signal switch_pkt_codec_mk2_2_data_in_ase_mesh1_top4_1_data3_out : std_logic_vector(31 downto 0);
	signal led_pkt_codec_mk2_1_stall_out_ase_mesh1_top4_1_stall0_in : std_logic;
	signal led_pkt_codec_mk2_1_stall_in_ase_mesh1_top4_1_stall0_out : std_logic;
	signal led_pkt_codec_mk2_2_stall_out_ase_mesh1_top4_1_stall1_in : std_logic;
	signal led_pkt_codec_mk2_2_stall_in_ase_mesh1_top4_1_stall1_out : std_logic;
	signal switch_pkt_codec_mk2_1_stall_out_ase_mesh1_top4_1_stall2_in : std_logic;
	signal switch_pkt_codec_mk2_1_stall_in_ase_mesh1_top4_1_stall2_out : std_logic;
	signal switch_pkt_codec_mk2_2_stall_out_ase_mesh1_top4_1_stall3_in : std_logic;
	signal switch_pkt_codec_mk2_2_stall_in_ase_mesh1_top4_1_stall3_out : std_logic;

	-- Top level for ase_mesh1 NoC with four agents.
	component ase_mesh1_top4
		port (
			clk : in std_logic;
			cmd0_in : in std_logic_vector(1 downto 0);
			cmd0_out : out std_logic_vector(1 downto 0);
			cmd1_in : in std_logic_vector(1 downto 0);
			cmd1_out : out std_logic_vector(1 downto 0);
			cmd2_in : in std_logic_vector(1 downto 0);
			cmd2_out : out std_logic_vector(1 downto 0);
			cmd3_in : in std_logic_vector(1 downto 0);
			cmd3_out : out std_logic_vector(1 downto 0);
			data0_in : in std_logic_vector(31 downto 0);
			data0_out : out std_logic_vector(31 downto 0);
			data1_in : in std_logic_vector(31 downto 0);
			data1_out : out std_logic_vector(31 downto 0);
			data2_in : in std_logic_vector(31 downto 0);
			data2_out : out std_logic_vector(31 downto 0);
			data3_in : in std_logic_vector(31 downto 0);
			data3_out : out std_logic_vector(31 downto 0);
			rst_n : in std_logic;
			stall0_in : in std_logic;
			stall0_out : out std_logic;
			stall1_in : in std_logic;
			stall1_out : out std_logic;
			stall2_in : in std_logic;
			stall2_out : out std_logic;
			stall3_in : in std_logic;
			stall3_out : out std_logic);
	end component;

	-- Inverts led for evey data word received.
	component led_pkt_codec_mk2
		port (
			clk : in std_logic;
			cmd_in : in std_logic_vector(1 downto 0);
			cmd_out : out std_logic_vector(1 downto 0);
			data_in : in std_logic_vector(31 downto 0);
			data_out : out std_logic_vector(31 downto 0);
			led_out : out std_logic;
			rst_n : in std_logic;
			stall_in : in std_logic;
			stall_out : out std_logic);
	end component;

	component switch_pkt_codec_mk2
		generic (
			target_id_g : integer := 0);
		port (
			clk : in std_logic;
			cmd_in : in std_logic_vector(1 downto 0);
			cmd_out : out std_logic_vector(1 downto 0);
			data_in : in std_logic_vector(31 downto 0);
			data_out : out std_logic_vector(31 downto 0);
			rst_n : in std_logic;
			stall_in : in std_logic;
			stall_out : out std_logic;
			switch_in : in std_logic);
	end component;



begin


	ase_mesh1_top4_1 : ase_mesh1_top4
		port map (
			cmd0_in(1 downto 0) => led_pkt_codec_mk2_1_cmd_out_ase_mesh1_top4_1_cmd0_in(1 downto 0),
			cmd0_out(1 downto 0) => led_pkt_codec_mk2_1_cmd_in_ase_mesh1_top4_1_cmd0_out(1 downto 0),
			cmd1_in(1 downto 0) => led_pkt_codec_mk2_2_cmd_out_ase_mesh1_top4_1_cmd1_in(1 downto 0),
			cmd1_out(1 downto 0) => led_pkt_codec_mk2_2_cmd_in_ase_mesh1_top4_1_cmd1_out(1 downto 0),
			cmd2_in(1 downto 0) => switch_pkt_codec_mk2_1_cmd_out_ase_mesh1_top4_1_cmd2_in(1 downto 0),
			cmd2_out(1 downto 0) => switch_pkt_codec_mk2_1_cmd_in_ase_mesh1_top4_1_cmd2_out(1 downto 0),
			cmd3_in(1 downto 0) => switch_pkt_codec_mk2_2_cmd_out_ase_mesh1_top4_1_cmd3_in(1 downto 0),
			cmd3_out(1 downto 0) => switch_pkt_codec_mk2_2_cmd_in_ase_mesh1_top4_1_cmd3_out(1 downto 0),
			data0_in(31 downto 0) => led_pkt_codec_mk2_1_data_out_ase_mesh1_top4_1_data0_in(31 downto 0),
			data0_out(31 downto 0) => led_pkt_codec_mk2_1_data_in_ase_mesh1_top4_1_data0_out(31 downto 0),
			data1_in(31 downto 0) => led_pkt_codec_mk2_2_data_out_ase_mesh1_top4_1_data1_in(31 downto 0),
			data1_out(31 downto 0) => led_pkt_codec_mk2_2_data_in_ase_mesh1_top4_1_data1_out(31 downto 0),
			data2_in(31 downto 0) => switch_pkt_codec_mk2_1_data_out_ase_mesh1_top4_1_data2_in(31 downto 0),
			data2_out(31 downto 0) => switch_pkt_codec_mk2_1_data_in_ase_mesh1_top4_1_data2_out(31 downto 0),
			data3_in(31 downto 0) => switch_pkt_codec_mk2_2_data_out_ase_mesh1_top4_1_data3_in(31 downto 0),
			data3_out(31 downto 0) => switch_pkt_codec_mk2_2_data_in_ase_mesh1_top4_1_data3_out(31 downto 0),
			stall0_in => led_pkt_codec_mk2_1_stall_out_ase_mesh1_top4_1_stall0_in,
			stall0_out => led_pkt_codec_mk2_1_stall_in_ase_mesh1_top4_1_stall0_out,
			stall1_in => led_pkt_codec_mk2_2_stall_out_ase_mesh1_top4_1_stall1_in,
			stall1_out => led_pkt_codec_mk2_2_stall_in_ase_mesh1_top4_1_stall1_out,
			stall2_in => switch_pkt_codec_mk2_1_stall_out_ase_mesh1_top4_1_stall2_in,
			stall2_out => switch_pkt_codec_mk2_1_stall_in_ase_mesh1_top4_1_stall2_out,
			stall3_in => switch_pkt_codec_mk2_2_stall_out_ase_mesh1_top4_1_stall3_in,
			stall3_out => switch_pkt_codec_mk2_2_stall_in_ase_mesh1_top4_1_stall3_out,
			clk => clk_CLK,
			rst_n => reset_RESETn);

	led_pkt_codec_mk2_1 : led_pkt_codec_mk2
		port map (
			cmd_in(1 downto 0) => led_pkt_codec_mk2_1_cmd_in_ase_mesh1_top4_1_cmd0_out(1 downto 0),
			cmd_out(1 downto 0) => led_pkt_codec_mk2_1_cmd_out_ase_mesh1_top4_1_cmd0_in(1 downto 0),
			data_in(31 downto 0) => led_pkt_codec_mk2_1_data_in_ase_mesh1_top4_1_data0_out(31 downto 0),
			data_out(31 downto 0) => led_pkt_codec_mk2_1_data_out_ase_mesh1_top4_1_data0_in(31 downto 0),
			stall_in => led_pkt_codec_mk2_1_stall_in_ase_mesh1_top4_1_stall0_out,
			stall_out => led_pkt_codec_mk2_1_stall_out_ase_mesh1_top4_1_stall0_in,
			clk => clk_CLK,
			led_out => led_1_gpio_out,
			rst_n => reset_RESETn);

	led_pkt_codec_mk2_2 : led_pkt_codec_mk2
		port map (
			cmd_in(1 downto 0) => led_pkt_codec_mk2_2_cmd_in_ase_mesh1_top4_1_cmd1_out(1 downto 0),
			cmd_out(1 downto 0) => led_pkt_codec_mk2_2_cmd_out_ase_mesh1_top4_1_cmd1_in(1 downto 0),
			data_in(31 downto 0) => led_pkt_codec_mk2_2_data_in_ase_mesh1_top4_1_data1_out(31 downto 0),
			data_out(31 downto 0) => led_pkt_codec_mk2_2_data_out_ase_mesh1_top4_1_data1_in(31 downto 0),
			stall_in => led_pkt_codec_mk2_2_stall_in_ase_mesh1_top4_1_stall1_out,
			stall_out => led_pkt_codec_mk2_2_stall_out_ase_mesh1_top4_1_stall1_in,
			clk => clk_CLK,
			led_out => led_gpio_out,
			rst_n => reset_RESETn);

	switch_pkt_codec_mk2_1 : switch_pkt_codec_mk2
		generic map (
			target_id_g => 0)
		port map (
			cmd_in(1 downto 0) => switch_pkt_codec_mk2_1_cmd_in_ase_mesh1_top4_1_cmd2_out(1 downto 0),
			cmd_out(1 downto 0) => switch_pkt_codec_mk2_1_cmd_out_ase_mesh1_top4_1_cmd2_in(1 downto 0),
			data_in(31 downto 0) => switch_pkt_codec_mk2_1_data_in_ase_mesh1_top4_1_data2_out(31 downto 0),
			data_out(31 downto 0) => switch_pkt_codec_mk2_1_data_out_ase_mesh1_top4_1_data2_in(31 downto 0),
			stall_in => switch_pkt_codec_mk2_1_stall_in_ase_mesh1_top4_1_stall2_out,
			stall_out => switch_pkt_codec_mk2_1_stall_out_ase_mesh1_top4_1_stall2_in,
			clk => clk_CLK,
			rst_n => reset_RESETn,
			switch_in => switch_gpio_out);

	switch_pkt_codec_mk2_2 : switch_pkt_codec_mk2
		generic map (
			target_id_g => 1)
		port map (
			cmd_in(1 downto 0) => switch_pkt_codec_mk2_2_cmd_in_ase_mesh1_top4_1_cmd3_out(1 downto 0),
			cmd_out(1 downto 0) => switch_pkt_codec_mk2_2_cmd_out_ase_mesh1_top4_1_cmd3_in(1 downto 0),
			data_in(31 downto 0) => switch_pkt_codec_mk2_2_data_in_ase_mesh1_top4_1_data3_out(31 downto 0),
			data_out(31 downto 0) => switch_pkt_codec_mk2_2_data_out_ase_mesh1_top4_1_data3_in(31 downto 0),
			stall_in => switch_pkt_codec_mk2_2_stall_in_ase_mesh1_top4_1_stall3_out,
			stall_out => switch_pkt_codec_mk2_2_stall_out_ase_mesh1_top4_1_stall3_in,
			clk => clk_CLK,
			rst_n => reset_RESETn,
			switch_in => switch_1_gpio_out);

end structural;

