// megafunction wizard: %ALTGX_RECONFIG%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: alt2gxb_reconfig 

// ============================================================
// File Name: altpcie_reconfig_3cgx.v
// Megafunction Name(s):
// 			alt2gxb_reconfig
//
// Simulation Library Files(s):
// 			
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 9.1 Build 304 01/25/2010 SP 1 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2010 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//alt2gxb_reconfig CBX_AUTO_BLACKBOX="ALL" DEVICE_FAMILY="Cyclone IV GX" ENABLE_BUF_CAL="TRUE" NUMBER_OF_CHANNELS=4 NUMBER_OF_RECONFIG_PORTS=1 RECONFIG_FROMGXB_WIDTH=5 RECONFIG_TOGXB_WIDTH=4 busy reconfig_clk reconfig_fromgxb reconfig_togxb
//VERSION_BEGIN 9.1SP1 cbx_alt2gxb_reconfig 2010:01:25:21:07:46:SJ cbx_alt_cal 2010:01:25:21:07:46:SJ cbx_alt_dprio 2010:01:25:21:07:46:SJ cbx_altsyncram 2010:01:25:21:07:46:SJ cbx_cycloneii 2010:01:25:21:07:46:SJ cbx_lpm_add_sub 2010:01:25:21:07:46:SJ cbx_lpm_compare 2010:01:25:21:07:46:SJ cbx_lpm_counter 2010:01:25:21:07:46:SJ cbx_lpm_decode 2010:01:25:21:07:46:SJ cbx_lpm_mux 2010:01:25:21:07:46:SJ cbx_lpm_shiftreg 2010:01:25:21:07:46:SJ cbx_mgl 2010:01:25:21:15:13:SJ cbx_stratix 2010:01:25:21:07:46:SJ cbx_stratixii 2010:01:25:21:07:46:SJ cbx_stratixiii 2010:01:25:21:07:46:SJ cbx_util_mgl 2010:01:25:21:07:46:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  altpcie_reconfig_3cgx_alt2gxb_reconfig_nlm
	( 
	busy,
	reconfig_clk,
	reconfig_fromgxb,
	reconfig_togxb) ;
	output   busy;
	input   reconfig_clk;
	input   [4:0]  reconfig_fromgxb;
	output   [3:0]  reconfig_togxb;

	wire  cal_busy;
	wire  is_adce_all_control;
	wire  is_adce_continuous_single_control;
	wire  is_adce_one_time_single_control;
	wire  is_adce_single_control;
	wire  is_adce_standby_single_control;

	assign
		busy = cal_busy,
		cal_busy = 1'b0,
		reconfig_togxb = {4{1'b0}};
endmodule //altpcie_reconfig_3cgx_alt2gxb_reconfig_nlm
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module altpcie_reconfig_3cgx (
	reconfig_clk,
	reconfig_fromgxb,
	busy,
	reconfig_togxb);

	input	  reconfig_clk;
	input	[4:0]  reconfig_fromgxb;
	output	  busy;
	output	[3:0]  reconfig_togxb;

	wire  sub_wire0;
	wire [3:0] sub_wire1;
	wire  busy = sub_wire0;
	wire [3:0] reconfig_togxb = sub_wire1[3:0];

	altpcie_reconfig_3cgx_alt2gxb_reconfig_nlm	altpcie_reconfig_3cgx_alt2gxb_reconfig_nlm_component (
				.reconfig_clk (reconfig_clk),
				.reconfig_fromgxb (reconfig_fromgxb),
				.busy (sub_wire0),
				.reconfig_togxb (sub_wire1));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ADCE NUMERIC "0"
// Retrieval info: PRIVATE: CMU_PLL NUMERIC "0"
// Retrieval info: PRIVATE: DATA_RATE NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone IV GX"
// Retrieval info: PRIVATE: PMA NUMERIC "0"
// Retrieval info: PRIVATE: PROTO_SWITCH NUMERIC "0"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
// Retrieval info: CONSTANT: CBX_BLACKBOX_LIST STRING "-lpm_mux"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone IV GX"
// Retrieval info: CONSTANT: NUMBER_OF_CHANNELS NUMERIC "4"
// Retrieval info: CONSTANT: NUMBER_OF_RECONFIG_PORTS NUMERIC "1"
// Retrieval info: CONSTANT: enable_buf_cal STRING "true"
// Retrieval info: CONSTANT: reconfig_fromgxb_width NUMERIC "5"
// Retrieval info: CONSTANT: reconfig_togxb_width NUMERIC "4"
// Retrieval info: USED_PORT: busy 0 0 0 0 OUTPUT NODEFVAL "busy"
// Retrieval info: USED_PORT: reconfig_clk 0 0 0 0 INPUT NODEFVAL "reconfig_clk"
// Retrieval info: USED_PORT: reconfig_fromgxb 0 0 5 0 INPUT NODEFVAL "reconfig_fromgxb[4..0]"
// Retrieval info: USED_PORT: reconfig_togxb 0 0 4 0 OUTPUT NODEFVAL "reconfig_togxb[3..0]"
// Retrieval info: CONNECT: @reconfig_fromgxb 0 0 5 0 reconfig_fromgxb 0 0 5 0
// Retrieval info: CONNECT: @reconfig_clk 0 0 0 0 reconfig_clk 0 0 0 0
// Retrieval info: CONNECT: reconfig_togxb 0 0 4 0 @reconfig_togxb 0 0 4 0
// Retrieval info: CONNECT: busy 0 0 0 0 @busy 0 0 0 0
// Retrieval info: GEN_FILE: TYPE_NORMAL altpcie_reconfig_3cgx.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL altpcie_reconfig_3cgx.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altpcie_reconfig_3cgx.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altpcie_reconfig_3cgx.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altpcie_reconfig_3cgx_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altpcie_reconfig_3cgx_bb.v TRUE
